### ISSUE TITLE
Close button behaviour complications

### ISSUE THREAD

**Issue by joshuapoq** [bambuser/BambuserPlayerSDK-iOS#11]
### Description
UPDATE: The close button logic is misleading but the button does work when PIP is disabled. However the current way the close button works is not really enough for users to be able to close the view without us adding our own way to close it. [See comment below](https://github.com/bambuser/BambuserPlayerSDK-iOS/issues/11#issuecomment-2223508717).

Using the `closeButton: .visible` UI configuration shows a down chevron in the top right corner. ~Tapping that chevron does nothing (no event is fired)~. It's not clear if the chevron relates to PiP or is meant as a modal dismiss close button.

Also the API to handle close is a bit tricky from the event closure. It might be better to switch to delegates like you are doing for the new API. See example below where I need to capture a closure to handle close (UIKit).

### Versions
- Xcode 15.3
- Bambuser 1.4.1

### Code
```swift
class BambuserFactory {
    func makeBambuserViewController(showId: String) -> UIViewController {
        var close: (() -> Void)?
        let viewController = BambuserPlayerViewController(showId: showId, config: .init(uiConfig: .init(closeButton: .visible))) { event in
            switch event {
            case .close:
                close?()
                
            default:
                print(event) // No event occurs when tapping the chevron.
            }
        }
        close = { [weak viewController] in viewController?.close() }
        return viewController
    }
}
```

**Comment by saeidbasirnia** [comment]
Hi, 

chevron only is shown if PiP is enabled in configuration setup:
`PlayerConfiguration.pipConfig.isEnabled == true`. 
Please note that PIP is not working in iPhone simulator at this point, you either need to test it on iPad or a real device
In this case, closing this view, should be handled by the developer.
if `PlayerConfiguration.pipConfig.isEnabled == false`, then there will be a X, at the top right corner.
Also thanks for your suggestion regarding the API and we'll look into this.

**Comment by joshuapoq** [comment]
Thanks for the explanation, that does make sense! I will test this out.

**Comment by saeidbasirnia** [comment]
I'll close this issue but feel free to open a new one if you have any issues.

**Comment by joshuapoq** [comment]
Hey @saeidbasirnia, I finally tested this out and it does work when disabling Picture in Picture but it's not a great experience.

There's no way to close the modal presentation when PIP is enabled when presenting fullscreen so we must either add our own close button over the PIP button or present within a navigation stack.

This problem is a bit more frustrating when it comes to safeArea. I'm not sure if it's the same for SwiftUI but using UIKit there's no way to present the video fullscreen but have the controls within the safe area. The uiConfig for `ignoresSafeArea` seems to do nothing.

There is also no close button on the end curtain screen after the video is finished.

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, 
Thanks for reporting this issue, I reported this to our team and we'll look into. 
I will get back to you soon.

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, 
These issues are resolved in [release 1.5.1](https://github.com/bambuser/BambuserPlayerSDK-iOS/releases/tag/1.5.1).
Please check and let me know if there's more issues.

**Comment by joshuapoq** [comment]
Works perfectly now! Great job, thanks! ❤️

**Comment by joshuapoq** [comment]
Would suggest maybe having the UI always abide by the `safeArea` so you don't have to add magic number padding (as the track at the bottom is now quite far away from the bottom and the header is still slightly too close to the safe area) but instead only use `ignoreSystemInsets` for the video layer but not the UI.

**Comment by joshuapoq** [comment]
Apologies @saeidbasirnia whilst the close button is now working on the video and curtain. It's still not showing for every state leading to users needing to force close the app (I'm not sure what state this video is in):
![BambuserMissingClose](https://github.com/user-attachments/assets/c0db1385-fceb-4378-9fe1-d6db5fed2f50)

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq, 
Thanks for your feedback and screenshots. 
We have some improvements and bug fixes coming up this week and it should cover these issues.

Beside the `upcoming show` view, did you face other places with similar issue?

**Comment by saeidbasirnia** [comment]
Hi @joshuapoq,
`BambuserPlayerSDK` [1.5.3](https://github.com/bambuser/BambuserPlayerSDK-iOS/tree/1.5.3) is now available and includes fixes for these issues.

**Comment by joshuapoq** [comment]
Works great, thanks!

**Comment by CTOverton** [comment]
@saeidbasirnia @joshuapoq, we were facing this similar issue in version 1.5.3 in our implementation. 

Can you provide a simple example just of what this implementation should look like so we can verify if out setup is wrong?


```swift
@objc(Bambuser)
class Bambuser: RCTEventEmitter {

    private var hasListeners = false

    @objc(playShow:)
    func playShow(_ showId: NSString) {
        DispatchQueue.main.async {
            guard let rootViewController = UIApplication.shared.windows.first?.rootViewController else {
                return
            }

            let config = PlayerConfiguration(pipConfig: .standard, uiConfig: .minimal, preferredLocale: Locale(identifier: "en-US"))
            let context = BambuserPlayerContext()

            let player = BambuserPlayerViewController(
                showId: showId as String,
                environment: .global,
                config: config,
                context: context
            ) { [weak self] event in
                self?.handleEvent(event)
            }

            rootViewController.present(player, animated: true, completion: nil) // We are not manually calling close, do we need to?
        }
    }
```

We did not manually call a close function, we expected the sdk to handle close itself. Is there anything we are missing here?

**Comment by saeidbasirnia** [comment]
Hi @CTOverton, 

> We did not manually call a close function

PlayerSDK will emit `close` event when close button is tapped, so you should implement logic to dismiss the player view when receiving this event.
Please take a look at `handlePlayerEvent` in `PlayerViewController.swift` in UIKit demo project.
